[package]
name = "csv_to_vcard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
serde = "1.0.0"
serde_derive = "1.0.0"
concat-string = "1.0.1"
